<section class="owl-carousel owl-theme" id="owlCarousel">
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/design/a-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/a-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/b-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/programming/b-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/design/d-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/design/f-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/management/a-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/q-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/e-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/x-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/k-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/u-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/programming/c-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/design/c-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/programming/d-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/c-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/l-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/programming/a-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/z-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/design/b-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/j-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/y-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/management/b-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/g-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/f-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/omar-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/d-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/h-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/t-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/n-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/r-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/v-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/p-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/i-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/o-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/design/e-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/s-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/w-unsplash.jpg')"></div>
    <div class="item" style="background-image: url('http://katrinsig.com/webIntern/images/landscape/m-unsplash.jpg')"></div>
</section>
